  - name: Launch the PostgreSQL database
    docker_container:
      name: my-db
      image: arthsf/tp-devops-db:latest
      env:
        POSTGRES_DB: "db"
        POSTGRES_USER: "usr"
        POSTGRES_PASSWORD: "pwd"
      networks:
        - name: my-network