  - name: Run HTTPD
    docker_container:
      name: httpd
      image: arthsf/tp-devops-httpd:latest
      state: started
      ports:
        - "80:80"
      networks:
        - name: my-network
    vars:
      ansible_python_interpreter: ../../usr/bin/python3
