  - name: Run HTTPD
    docker_container:
      name: httpd
      image: arthsf/tp-devops-http-server:latest
      ports:
        - "80:80"
      networks:
        - name: my-network
      depends_on:
        - my-api
